/*
 *  BSD 2-Clause License - see ./LICENSE for details.
 */

// This is a generated file. Not intended for manual editing.
package taclanguage.autogenerated.psi;

import java.util.List;
import org.jetbrains.annotations.*;
import com.intellij.psi.PsiElement;

public interface TACClassHead extends PsiElement {

  @NotNull
  List<TACJType> getJTypeList();

  @Nullable
  TACModifierV getModifierV();

  @NotNull
  PsiElement getJavatypehead();

}
