// This is a generated file. Not intended for manual editing.
package taclanguage.autogenerated.psi;

import java.util.List;
import org.jetbrains.annotations.*;
import com.intellij.psi.PsiElement;

public interface TACCastIntr extends PsiElement {

  @Nullable
  TACJType getJType();

  @NotNull
  PsiElement getLbracket();

  @NotNull
  PsiElement getLevel();

  @Nullable
  PsiElement getPrimitivetype();

  @NotNull
  PsiElement getRbracket();

}
