// This is a generated file. Not intended for manual editing.
package taclanguage.autogenerated.psi;

import com.intellij.psi.PsiElement;
import java.util.List;
import org.jetbrains.annotations.*;

public interface TACClassHead extends PsiElement {

  @NotNull
  List<TACJType> getJTypeList();

  @Nullable
  TACModifierV getModifierV();

  @NotNull
  PsiElement getJavatypehead();
}
