// This is a generated file. Not intended for manual editing.
package taclanguage.autogenerated.psi;

import com.intellij.psi.PsiElement;
import com.intellij.psi.PsiReference;
import org.jetbrains.annotations.*;
import taclanguage.psi.TACNamedElement;

public interface TACDefMethodName extends TACNamedElement {

  @NotNull
  PsiElement getStringvar();

  @Nullable
  String getStringVar();

  String getName();

  @Nullable
  PsiElement getNameIdentifier();

  @NotNull
  PsiReference[] getReferences();
}
