// This is a generated file. Not intended for manual editing.
package taclanguage.autogenerated.psi;

import com.intellij.psi.PsiElement;
import java.util.List;
import org.jetbrains.annotations.*;

public interface TACEQInstr extends PsiElement {

  @NotNull
  TACLeftSide getLeftSide();

  @NotNull
  List<TACRightSide> getRightSideList();

  @Nullable
  PsiElement getOperators();
}
