// This is a generated file. Not intended for manual editing.
package taclanguage.autogenerated.psi;

import com.intellij.psi.PsiElement;
import java.util.List;
import org.jetbrains.annotations.*;

public interface TACInnerTable extends PsiElement {

  @NotNull
  List<TACModifierV> getModifierVList();

  @NotNull
  List<TACType> getTypeList();
}
