// This is a generated file. Not intended for manual editing.
package taclanguage.autogenerated.psi;

import java.util.List;
import org.jetbrains.annotations.*;
import com.intellij.psi.PsiElement;
import taclanguage.psi.TACNamedElement;
import com.intellij.psi.PsiReference;

public interface TACJType extends TACNamedElement {

  @Nullable
  String getJavaType();

  String getName();

  PsiElement setName(String newName);

  @Nullable
  PsiElement getNameIdentifier();

  PsiReference[] getReferences();

}
