// This is a generated file. Not intended for manual editing.
package taclanguage.autogenerated.psi;

import java.util.List;
import org.jetbrains.annotations.*;
import com.intellij.psi.PsiElement;
import taclanguage.psi.TACNamedElement;
import com.intellij.navigation.ItemPresentation;

public interface TACMethodDeclaration extends TACNamedElement {

  @NotNull
  List<TACAnnotation> getAnnotationList();

  @NotNull
  List<TACInstr> getInstrList();

  @NotNull
  TACMethodHead getMethodHead();

  @NotNull
  PsiElement getLbracket();

  @NotNull
  PsiElement getRbracket();

  String getName();

  PsiElement getNameIdentifier();

  ItemPresentation getPresentation();

  void navigate(boolean requestFocus);

}
