// This is a generated file. Not intended for manual editing.
package taclanguage.autogenerated.psi;

import java.util.List;
import org.jetbrains.annotations.*;
import com.intellij.psi.PsiElement;

public interface TACParams extends PsiElement {

  @NotNull
  List<TACAnnotation> getAnnotationList();

  @NotNull
  List<TACType> getTypeList();

  @Nullable
  PsiElement getLbracket();

  @Nullable
  PsiElement getRbracket();

}
