// This is a generated file. Not intended for manual editing.
package taclanguage.autogenerated.psi;

import com.intellij.psi.PsiElement;
import org.jetbrains.annotations.*;

public interface TACSwitchInst extends PsiElement {

  @NotNull
  PsiElement getLevel();
}
