// This is a generated file. Not intended for manual editing.
package taclanguage.autogenerated.psi;

import org.jetbrains.annotations.*;
import com.intellij.psi.PsiElement;

public interface TACSwitchInst extends PsiElement {

  @NotNull
  PsiElement getLevel();

}
