// This is a generated file. Not intended for manual editing.
package taclanguage.autogenerated.psi;

import com.intellij.psi.PsiElement;
import org.jetbrains.annotations.*;

public interface TACType extends PsiElement {

  @Nullable
  TACJType getJType();

  @Nullable
  TACLambdaType getLambdaType();

  @Nullable
  PsiElement getPrimitivetype();
}
