/*
 *  BSD 2-Clause License - see ./LICENSE for details.
 */

package taclanguage.autogenerated.lexer;

import com.intellij.lexer.FlexAdapter;

public class TAC_adapter extends FlexAdapter {

  public TAC_adapter() {
    super(new TACLexer(null));
  }
}
