// This is a generated file. Not intended for manual editing.
package JavaByteCodeLanguage.autoGenerated.psi;

import org.jetbrains.annotations.*;
import com.intellij.psi.PsiElement;

public interface JavaByteCodeLocVarTypeTableBody extends PsiElement {

  @NotNull
  PsiElement getLbracket();

  @NotNull
  PsiElement getRbracket();

}
