// This is a generated file. Not intended for manual editing.
package JavaByteCodeLanguage.autoGenerated.psi;

import com.intellij.psi.PsiElement;
import org.jetbrains.annotations.*;

public interface JavaByteCodeLocVarTypeTableBody extends PsiElement {

  @NotNull
  PsiElement getLbracket();

  @NotNull
  PsiElement getRbracket();
}
