// This is a generated file. Not intended for manual editing.
package JavaByteCodeLanguage.autoGenerated.psi;

import java.util.List;

import JavaByteCodeLanguage.psi.JavaByteCodeNamedElement;
import org.jetbrains.annotations.*;
import com.intellij.psi.PsiElement;
import com.intellij.navigation.ItemPresentation;

public interface JavaByteCodeMethodDeclaration extends JavaByteCodeNamedElement {

  @NotNull
  List<JavaByteCodeInstructionBody> getInstructionBodyList();

  @NotNull
  List<JavaByteCodeLocVarTableDeclaration> getLocVarTableDeclarationList();

  @NotNull
  JavaByteCodeMethodHead getMethodHead();

  @NotNull
  List<JavaByteCodeStackMapTableDeclaration> getStackMapTableDeclarationList();

  @NotNull
  PsiElement getLbracket();

  @NotNull
  PsiElement getRbracket();

  String getName();

  PsiElement setName(String newName);

  PsiElement getNameIdentifier();

  ItemPresentation getPresentation();

  void navigate(boolean requestFocus);

}
