// This is a generated file. Not intended for manual editing.
package JavaByteCodeLanguage.autoGenerated.psi;

import java.util.List;
import org.jetbrains.annotations.*;
import com.intellij.psi.PsiElement;

public interface JavaByteCodeMethodArea extends PsiElement {

  @NotNull
  List<JavaByteCodeMethodDeclaration> getMethodDeclarationList();

  @NotNull
  PsiElement getLbracket();

  @NotNull
  PsiElement getRbracket();

}
