// This is a generated file. Not intended for manual editing.
package JavaByteCodeLanguage.autoGenerated.psi;

import java.util.List;
import org.jetbrains.annotations.*;
import com.intellij.psi.PsiElement;
import JavaByteCodeLanguage.psi.JavaByteCodeNamedElement;
import com.intellij.psi.PsiReference;

public interface JavaByteCodeDefMethodName extends JavaByteCodeNamedElement {

  @NotNull
  PsiElement getStringvar();

  @Nullable
  String getStringVar();

  String getName();

  PsiElement setName(String newName);

  @Nullable
  PsiElement getNameIdentifier();

  @NotNull
  PsiReference[] getReferences();

}
