// This is a generated file. Not intended for manual editing.
package JavaByteCodeLanguage.autoGenerated.psi;

import java.util.List;
import org.jetbrains.annotations.*;
import com.intellij.psi.PsiElement;

public interface JavaByteCodeInstructionBody extends PsiElement {

  @NotNull
  JavaByteCodeInstr getInstr();

  @NotNull
  JavaByteCodeLineNumber getLineNumber();

  @NotNull
  JavaByteCodePcNumber getPcNumber();

}
