// This is a generated file. Not intended for manual editing.
package JavaByteCodeLanguage.autoGenerated.psi;

import com.intellij.psi.PsiElement;
import java.util.List;
import org.jetbrains.annotations.*;

public interface JavaByteCodeInstr extends PsiElement {

  @Nullable
  JavaByteCodeJType getJType();

  @NotNull
  List<JavaByteCodeJavaOP> getJavaOPList();

  @Nullable
  JavaByteCodeType getType();

  @Nullable
  PsiElement getLoadInstr();

  @Nullable
  PsiElement getMnemonic();

  @Nullable
  PsiElement getNumber();
}
