/*
 *  BSD 2-Clause License - see ./LICENSE for details.
 */

// This is a generated file. Not intended for manual editing.
package JavaByteCodeLanguage.autoGenerated.psi;

import JavaByteCodeLanguage.psi.JavaByteCodeNamedElement;
import com.intellij.psi.PsiElement;
import com.intellij.psi.PsiReference;
import org.jetbrains.annotations.*;

public interface JavaByteCodeDefMethodName extends JavaByteCodeNamedElement {

  @NotNull
  PsiElement getStringvar();

  @Nullable
  String getStringVar();

  String getName();

  @Nullable
  PsiElement getNameIdentifier();

  @NotNull
  PsiReference[] getReferences();
}
