// This is a generated file. Not intended for manual editing.
package JavaByteCodeLanguage.autoGenerated.psi;

import com.intellij.psi.PsiElement;
import org.jetbrains.annotations.*;

public interface JavaByteCodeTableArea extends PsiElement {

  @Nullable
  JavaByteCodeExceptionTableDeclaration getExceptionTableDeclaration();

  @Nullable
  JavaByteCodeLocVarTableDeclaration getLocVarTableDeclaration();

  @Nullable
  JavaByteCodeLocVarTypeTableDeclaration getLocVarTypeTableDeclaration();

  @Nullable
  JavaByteCodeStackMapTableDeclaration getStackMapTableDeclaration();

  @NotNull
  PsiElement getLbracket();

  @NotNull
  PsiElement getRbracket();
}
