/*
 *  BSD 2-Clause License - see ./LICENSE for details.
 */

// This is a generated file. Not intended for manual editing.
package JavaByteCodeLanguage.autoGenerated.psi;

import java.util.List;
import org.jetbrains.annotations.*;
import com.intellij.psi.PsiElement;

public interface JavaByteCodeAttributesArea extends PsiElement {

  @Nullable
  JavaByteCodeInnerTable getInnerTable();

  @NotNull
  PsiElement getLbracket();

  @NotNull
  PsiElement getRbracket();

}
