// This is a generated file. Not intended for manual editing.
package org.opalj.intellijintegration.JavaByteCodeLanguage.autoGenerated.psi;

import com.intellij.psi.PsiElement;
import org.jetbrains.annotations.*;

public interface JavaByteCodeExceptionTableBody extends PsiElement {

  @Nullable
  JavaByteCodeType getType();

  @NotNull
  PsiElement getLbracket();

  @NotNull
  PsiElement getRbracket();

  @Nullable
  PsiElement getStringvar();
}
