// This is a generated file. Not intended for manual editing.
package org.opalj.intellijintegration.JavaByteCodeLanguage.autoGenerated.psi;

import com.intellij.psi.PsiElement;
import org.jetbrains.annotations.*;

public interface JavaByteCodeMethodHead extends PsiElement {

  @NotNull
  JavaByteCodeMethodName getMethodName();

  @Nullable
  JavaByteCodeModifierV getModifierV();

  @NotNull
  JavaByteCodeType getType();
}
