// This is a generated file. Not intended for manual editing.
package org.opalj.intellijintegration.JavaByteCodeLanguage.autoGenerated.psi;

import com.intellij.psi.PsiElement;
import java.util.List;
import org.jetbrains.annotations.*;

public interface JavaByteCodeJavaOP extends PsiElement {

  @NotNull
  List<JavaByteCodeMethodName> getMethodNameList();

  @NotNull
  List<JavaByteCodeType> getTypeList();

  @Nullable
  PsiElement getNumber();
}
