package Actions;

import JavaByteCodeLanguage.autoGenerated.psi.JavaByteCodeClassHead;
import JavaByteCodeLanguage.autoGenerated.psi.JavaByteCodeInstructionBody;
import com.intellij.openapi.actionSystem.AnAction;
import com.intellij.openapi.actionSystem.AnActionEvent;
import com.intellij.openapi.actionSystem.CommonDataKeys;
import com.intellij.openapi.editor.Document;
import com.intellij.openapi.editor.Editor;
import com.intellij.openapi.fileEditor.FileEditorManager;
import com.intellij.openapi.fileEditor.OpenFileDescriptor;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.vfs.VirtualFile;
import com.intellij.psi.*;
import com.intellij.psi.util.PsiTreeUtil;

import java.util.Objects;

/**
 * Jumps from a given Instruction to the source file and set the caret to given line number
 */
public class JumpToSource extends AnAction {

    @Override
    public void update(AnActionEvent e) {
        super.update(e);

        Project project = e.getProject();
        VirtualFile jbcFile = e.getData(CommonDataKeys.VIRTUAL_FILE);

        // this action should only work for bytecode
        e.getPresentation().setEnabledAndVisible(project != null && jbcFile != null && jbcFile.getExtension() != null
            && jbcFile.getExtension().equals("jbc"));
    }

    @Override
    public void actionPerformed(AnActionEvent e) {
        Project project = e.getProject();
        Editor editor = e.getData(CommonDataKeys.EDITOR);
        PsiFile psiFile = e.getData(CommonDataKeys.PSI_FILE);
        if(editor == null || psiFile == null || project == null){
            return ;
        }
        PsiElement elementAt = psiFile.findElementAt(editor.getCaretModel().getOffset());
        JavaByteCodeInstructionBody parent =
                PsiTreeUtil.getParentOfType(elementAt, JavaByteCodeInstructionBody.class);
        if(parent == null){
            return;
        }
        int lineNumber = Integer.parseInt(parent.getLineNumber().getNumber().getText());
        PsiElement fullyQualifiedClass = null;
        for (PsiElement child : psiFile.getChildren()) {
            if(child instanceof  JavaByteCodeClassHead){
                if(((JavaByteCodeClassHead)child).getJTypeList().size() > 0)
                fullyQualifiedClass = ((JavaByteCodeClassHead)child).getJTypeList().get(0);
                break;
            }
        }
        if(fullyQualifiedClass != null){
            // e.g. java.lang.String -> resolve = String
            PsiElement resolve = fullyQualifiedClass.getReferences()[fullyQualifiedClass.getReferences().length - 1].resolve();
            Document document = PsiDocumentManager.getInstance(project).getDocument(Objects.requireNonNull(resolve).getContainingFile());
            int lineStartOffset = Objects.requireNonNull(document).getLineStartOffset(lineNumber-1);
            FileEditorManager.getInstance(project).openTextEditor(
                    new OpenFileDescriptor(project,
                            resolve.getContainingFile().getVirtualFile(),
                            lineStartOffset
                    ),true);
        }
    }
}
