// This is a generated file. Not intended for manual editing.
package org.opalj.intellijintegration.taclanguage.autogenerated.psi;

import com.intellij.navigation.ItemPresentation;
import com.intellij.psi.PsiElement;
import org.jetbrains.annotations.*;
import org.opalj.intellijintegration.taclanguage.psi.TACNamedElement;

public interface TACFieldsDeclaration extends TACNamedElement {

  @NotNull
  TACDefMethodName getDefMethodName();

  @Nullable
  TACModifierV getModifierV();

  @NotNull
  TACType getType();

  String getName();

  PsiElement getNameIdentifier();

  ItemPresentation getPresentation();

  void navigate(boolean requestFocus);
}
