// This is a generated file. Not intended for manual editing.
package org.opalj.intellijintegration.taclanguage.autogenerated.psi;

import com.intellij.psi.PsiElement;
import org.jetbrains.annotations.*;

public interface TACLambdaType extends PsiElement {

  @NotNull
  TACLambdaParams getLambdaParams();

  @NotNull
  PsiElement getNumber();
}
