// This is a generated file. Not intended for manual editing.
package org.opalj.intellijintegration.taclanguage.autogenerated.psi;

import com.intellij.psi.PsiElement;
import org.jetbrains.annotations.*;

public interface TACLambdaParams extends PsiElement {

  @NotNull
  PsiElement getLbracket();

  @NotNull
  PsiElement getRbracket();
}
