// This is a generated file. Not intended for manual editing.
package org.opalj.intellijintegration.taclanguage.autogenerated.psi;

import com.intellij.psi.PsiElement;
import org.jetbrains.annotations.*;

public interface TACLevels extends PsiElement {

  @NotNull
  TACArrayOrBracket getArrayOrBracket();

  @Nullable
  TACJType getJType();

  @NotNull
  PsiElement getLevel();
}
