/*
 *  BSD 2-Clause License - see ./LICENSE for details.
 */

package org.opalj.intellijintegration.taclanguage.autogenerated.parser;

import com.intellij.lang.parser.GeneratedParserUtilBase;

public class TAC_parserParserUtil extends GeneratedParserUtilBase {}
