// This is a generated file. Not intended for manual editing.
package org.opalj.intellijintegration.taclanguage.autogenerated.psi.impl;

import com.intellij.lang.ASTNode;
import com.intellij.psi.PsiElement;
import com.intellij.psi.PsiElementVisitor;
import com.intellij.psi.PsiReference;
import org.jetbrains.annotations.*;
import org.opalj.intellijintegration.taclanguage.autogenerated.psi.TACJType;
import org.opalj.intellijintegration.taclanguage.autogenerated.psi.TACVisitor;
import org.opalj.intellijintegration.taclanguage.psi.impl.TACNamedElementImpl;
import org.opalj.intellijintegration.taclanguage.psi.impl.TAC_parserParserUtil;

public class TACJTypeImpl extends TACNamedElementImpl implements TACJType {

  public TACJTypeImpl(@NotNull ASTNode node) {
    super(node);
  }

  public void accept(@NotNull TACVisitor visitor) {
    visitor.visitJType(this);
  }

  public void accept(@NotNull PsiElementVisitor visitor) {
    if (visitor instanceof TACVisitor) accept((TACVisitor) visitor);
    else super.accept(visitor);
  }

  @Override
  @Nullable
  public String getJavaType() {
    return TAC_parserParserUtil.getJavaType(this);
  }

  @Override
  public String getName() {
    return TAC_parserParserUtil.getName(this);
  }

  @Override
  @Nullable
  public PsiElement getNameIdentifier() {
    return TAC_parserParserUtil.getNameIdentifier(this);
  }

  @Override
  public PsiReference[] getReferences() {
    return TAC_parserParserUtil.getReferences(this);
  }
}
