// This is a generated file. Not intended for manual editing.
package org.opalj.intellijintegration.taclanguage.autogenerated.psi.impl;

import static org.opalj.intellijintegration.taclanguage.autogenerated.psi.TAC_elementTypeHolder.*;

import com.intellij.extapi.psi.ASTWrapperPsiElement;
import com.intellij.lang.ASTNode;
import com.intellij.psi.PsiElement;
import com.intellij.psi.PsiElementVisitor;
import org.jetbrains.annotations.*;
import org.opalj.intellijintegration.taclanguage.autogenerated.psi.TACJType;
import org.opalj.intellijintegration.taclanguage.autogenerated.psi.TACLambdaType;
import org.opalj.intellijintegration.taclanguage.autogenerated.psi.TACType;
import org.opalj.intellijintegration.taclanguage.autogenerated.psi.TACVisitor;

public class TACTypeImpl extends ASTWrapperPsiElement implements TACType {

  public TACTypeImpl(@NotNull ASTNode node) {
    super(node);
  }

  public void accept(@NotNull TACVisitor visitor) {
    visitor.visitType(this);
  }

  public void accept(@NotNull PsiElementVisitor visitor) {
    if (visitor instanceof TACVisitor) accept((TACVisitor) visitor);
    else super.accept(visitor);
  }

  @Override
  @Nullable
  public TACJType getJType() {
    return findChildByClass(TACJType.class);
  }

  @Override
  @Nullable
  public TACLambdaType getLambdaType() {
    return findChildByClass(TACLambdaType.class);
  }

  @Override
  @Nullable
  public PsiElement getPrimitivetype() {
    return findChildByType(PRIMITIVETYPE);
  }
}
