// This is a generated file. Not intended for manual editing.
package taclanguage.autogenerated.psi.impl;

import com.intellij.extapi.psi.ASTWrapperPsiElement;
import com.intellij.lang.ASTNode;
import com.intellij.psi.PsiElementVisitor;
import com.intellij.psi.util.PsiTreeUtil;
import java.util.List;
import org.jetbrains.annotations.*;
import taclanguage.autogenerated.psi.*;

public class TACInstrImpl extends ASTWrapperPsiElement implements TACInstr {

  public TACInstrImpl(@NotNull ASTNode node) {
    super(node);
  }

  public void accept(@NotNull TACVisitor visitor) {
    visitor.visitInstr(this);
  }

  public void accept(@NotNull PsiElementVisitor visitor) {
    if (visitor instanceof TACVisitor) accept((TACVisitor) visitor);
    else super.accept(visitor);
  }

  @Override
  @NotNull
  public List<TACSwitchInst> getSwitchInstList() {
    return PsiTreeUtil.getChildrenOfTypeAsList(this, TACSwitchInst.class);
  }
}
