/*
 *  BSD 2-Clause License - see ./LICENSE for details.
 */

// This is a generated file. Not intended for manual editing.
package taclanguage.autogenerated.psi.impl;

import java.util.List;
import org.jetbrains.annotations.*;
import com.intellij.lang.ASTNode;
import com.intellij.psi.PsiElement;
import com.intellij.psi.PsiElementVisitor;
import com.intellij.psi.util.PsiTreeUtil;
import static taclanguage.autogenerated.psi.TAC_elementTypeHolder.*;
import com.intellij.extapi.psi.ASTWrapperPsiElement;
import taclanguage.autogenerated.psi.*;
import taclanguage.psi.impl.TAC_parserParserUtil;

public class TACInnerTableImpl extends ASTWrapperPsiElement implements TACInnerTable {

  public TACInnerTableImpl(@NotNull ASTNode node) {
    super(node);
  }

  public void accept(@NotNull TACVisitor visitor) {
    visitor.visitInnerTable(this);
  }

  public void accept(@NotNull PsiElementVisitor visitor) {
    if (visitor instanceof TACVisitor) accept((TACVisitor)visitor);
    else super.accept(visitor);
  }

  @Override
  @NotNull
  public List<TACModifierV> getModifierVList() {
    return PsiTreeUtil.getChildrenOfTypeAsList(this, TACModifierV.class);
  }

  @Override
  @NotNull
  public List<TACType> getTypeList() {
    return PsiTreeUtil.getChildrenOfTypeAsList(this, TACType.class);
  }

}
